### ISSUE TITLE
Error when using camera input

### ISSUE THREAD

**Issue by DavidRobbNZ** [nathanrooy/rpi-urban-mobility-tracker#1]
I'm new to using the rpi-umt, and have just installed the new umt version. When I run it on the video or stills, it classifies happily, but when I run using the camera input I'm getting the following error. The camera seems to work fine if I capture images using raspistill. Any ideas?

david@r2:~ $ source venv/bin/activate
(venv) david@r2:~ $ umt -camera
> INITIALIZING UMT...
   > THRESHOLD: 0.5
   > TPU = FALSE
   > CUSTOM DETECTOR = FALSE
   > CUSTOM LABEL MAP = FALSE

> TRACKING...
> starting video stream...
> FRAME: 0
Traceback (most recent call last):
  File "/home/david/venv/bin/umt", line 8, in <module>
    sys.exit(main())
  File "/home/david/venv/lib/python3.7/site-packages/umt/umt_main.py", line 77, in main
    new_dets, classes, scores = generate_detections(pil_img, interpreter, args.threshold)
ValueError: not enough values to unpack (expected 3, got 0)

**Comment by DavidRobbNZ** [comment]
Update: I've done some experimentation, and it appears that as long as the first image umt sees produces something to track, it's ok. I captured some video of my local street, and it gave the same error as I saw with the camera. But if I cut the video to start when there's a car in shot, it runs happily.

If I changed out the get detections call for a try/except, it doesn't fall into this trap.

           # get detections
            try:
              new_dets, classes, scores = generate_detections(pil_img, interpreter, args.threshold)
            except:
              continue

**Comment by nathanrooy** [comment]
Hi @DavidRobbNZ , I went ahead and implemented a slightly different check but it fixes the same thing: https://github.com/nathanrooy/rpi-urban-mobility-tracker/commit/6652798d588f68f09c250bcb36f24ed248125f38
