### ISSUE TITLE
Using TPU: AttributeError: 'Delegate' object has no attribute '_library'

### ISSUE THREAD

**Issue by airqualityanthony** [nathanrooy/rpi-urban-mobility-tracker#17]
Running the docker as per the file instructions - RPi 4 with a TPI.

Trying to run the command:
umt -video highway_01.mp4  -tpu 

I get the following: 
```
> INITIALIZING UMT...
   > THRESHOLD: 0.5
   > CUSTOM LABEL MAP = FALSE
   > TPU = TRUE
   > CUSTOM DETECTOR = FALSE
Traceback (most recent call last):
  File "/usr/local/bin/umt", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/umt/umt_main.py", line 62, in main
    interpreter = initialize_detector(args)
  File "/usr/local/lib/python3.7/dist-packages/umt/umt_utils.py", line 110, in initialize_detector
    {'device': device[0]} if device else {})
  File "/usr/local/lib/python3.7/dist-packages/tflite_runtime/interpreter.py", line 152, in load_delegate
    delegate = Delegate(library, options)
  File "/usr/local/lib/python3.7/dist-packages/tflite_runtime/interpreter.py", line 81, in __init__
    self._library = ctypes.pydll.LoadLibrary(library)
  File "/usr/lib/python3.7/ctypes/__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libedgetpu.so.1: cannot open shared object file: No such file or directory
Exception ignored in: <function Delegate.__del__ at 0xa819b198>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tflite_runtime/interpreter.py", line 116, in __del__
    if self._library is not None:
AttributeError: 'Delegate' object has no attribute '_library'

```

It works fine when I run without the tpu argument. I have the tpu installed correctly, and works for other code outside the docker. 

Any help? 

Thanks,

Anthony

**Comment by airqualityanthony** [comment]
@nathanrooy I'll close out, suggest the above changes to be implemented for latest installation. Feel free to check and edit if necessary.
